import { motion, useAnimation } from "framer-motion";
import { useInView } from "react-intersection-observer";
import { useEffect } from "react";
import Head from "next/head";
import { NextPage } from "next";
import Timeline from "../components/timeline";
import Image from "next/image";
import SkillsGrid from "../components/skillsGrid";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#c2edcd] to-[#387f87]">
        <div className="h-screen">
          <Image src={"/mestaring.jpg"} fill alt={""} className='object-cover'/>
        </div>
        
        <Timeline/>
        <SkillsGrid />
        <div className="h-64"></div>
      </main>
    </>
  );
};

export default Home;
